name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0/4 * * *"
  pull_request:
    branches:
      - main
    paths:
      - src/*
      - model/*
      - src/job.yml
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: List files in the repository
      run: ls -R
    - name: Run Azure ML Job
      run: az ml job create -f src/job.yml
      working-directory: ./src


