name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - src/*
      - model/*
      - src/job.yml
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: List files in the repository
      run: ls -R
    - name: Replace placeholder in job.yml
      run: sed -i 's|PLACEHOLDER_FOR_URI|${{secrets.AZURE_ML_DATASTORE_URI}}|g' src/job.yml
    - name: Change to source directory where yml is located
      run: cd ./src
    - name: Run Azure ML Job
      run: az ml job create -f job.yml --resource-group <place-holder-rg> --workspace-name <workspace-name>
      working-directory: ./src


